//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceShooter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class iResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal iResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceShooter.iResource", typeof(iResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATENEA&apos;S GAUNTLET.
        /// </summary>
        internal static string AteneaGauntlet {
            get {
                return ResourceManager.GetString("AteneaGauntlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +200% REAR ARMOR.
        /// </summary>
        internal static string AteneaGauntletDescription {
            get {
                return ResourceManager.GetString("AteneaGauntletDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIGA ARMOR.
        /// </summary>
        internal static string BeamArmor {
            get {
                return ResourceManager.GetString("BeamArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}% ARMOR VS. BEAMS.
        /// </summary>
        internal static string BeamArmorDescription {
            get {
                return ResourceManager.GetString("BeamArmorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLESO RAIL CHAMBER.
        /// </summary>
        internal static string BlesoRailChamber {
            get {
                return ResourceManager.GetString("BlesoRailChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}% PROJECTILE SPEED.
        /// </summary>
        internal static string BlesoRailChamberDescription {
            get {
                return ResourceManager.GetString("BlesoRailChamberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAS CARGADOR.
        /// </summary>
        internal static string Boot {
            get {
                return ResourceManager.GetString("Boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TENDER LOVING FIREPOWER.
        /// </summary>
        internal static string BootDescription {
            get {
                return ResourceManager.GetString("BootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTOS ARMOR.
        /// </summary>
        internal static string BotosShield {
            get {
                return ResourceManager.GetString("BotosShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}% BOTTOM ARMOR.
        /// </summary>
        internal static string BotosShieldDescription {
            get {
                return ResourceManager.GetString("BotosShieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL-SEEING EYE.
        /// </summary>
        internal static string Eyeball {
            get {
                return ResourceManager.GetString("Eyeball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOY OF REGENERATION.
        /// </summary>
        internal static string EyeballDescription {
            get {
                return ResourceManager.GetString("EyeballDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFRODITA&apos;S GAUNTLET.
        /// </summary>
        internal static string Gauntlet {
            get {
                return ResourceManager.GetString("Gauntlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +200% BOTTOM ARMOR.
        /// </summary>
        internal static string GauntletDescription {
            get {
                return ResourceManager.GetString("GauntletDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRUJA HEART.
        /// </summary>
        internal static string Heart {
            get {
                return ResourceManager.GetString("Heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELICIOUS INVINCIBILITY.
        /// </summary>
        internal static string HeartDescription {
            get {
                return ResourceManager.GetString("HeartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAMAL AUTO DOC.
        /// </summary>
        internal static string JamalAutoDoc {
            get {
                return ResourceManager.GetString("JamalAutoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} HEALTH REGENERATION.
        /// </summary>
        internal static string JamalAutoDocDescription {
            get {
                return ResourceManager.GetString("JamalAutoDocDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KESHIA SUBLIGHT ENGINE.
        /// </summary>
        internal static string KeshiaEngine {
            get {
                return ResourceManager.GetString("KeshiaEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% MOVE SPEED.
        /// </summary>
        internal static string KeshiaEngineDescription {
            get {
                return ResourceManager.GetString("KeshiaEngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RASHAD FIRE CONTROL.
        /// </summary>
        internal static string RashadFireCon {
            get {
                return ResourceManager.GetString("RashadFireCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% FIRE RATE.
        /// </summary>
        internal static string RashadFireConDescription {
            get {
                return ResourceManager.GetString("RashadFireConDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROACH ARMOR.
        /// </summary>
        internal static string RoachShield {
            get {
                return ResourceManager.GetString("RoachShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}% REAR ARMOR.
        /// </summary>
        internal static string RoachShieldDescription {
            get {
                return ResourceManager.GetString("RoachShieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTEM OF MECA LECA.
        /// </summary>
        internal static string Totem {
            get {
                return ResourceManager.GetString("Totem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVINCIBLE VS. BEAMS.
        /// </summary>
        internal static string TotemDescription {
            get {
                return ResourceManager.GetString("TotemDescription", resourceCulture);
            }
        }
    }
}
